// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGwsUhSEdp7IspSBqkGkTTN5hBvW0QJT4',
    appId: '1:650924033105:web:76339e7e537ab8aea62470',
    messagingSenderId: '650924033105',
    projectId: 'fanitmdtest',
    authDomain: 'fanitmdtest.firebaseapp.com',
    storageBucket: 'fanitmdtest.firebasestorage.app',
    measurementId: 'G-X5K5X82BY1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4cN8L20OZq5raTVOJMBkML14pfwYLfB8',
    appId: '1:650924033105:android:e117bfbf05d60763a62470',
    messagingSenderId: '650924033105',
    projectId: 'fanitmdtest',
    storageBucket: 'fanitmdtest.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCx6odV2p8D6ILilYBIN-dOPeAt8IyjcMw',
    appId: '1:650924033105:ios:334a4226510d3214a62470',
    messagingSenderId: '650924033105',
    projectId: 'fanitmdtest',
    storageBucket: 'fanitmdtest.firebasestorage.app',
    iosBundleId: 'com.example.fanitMdtest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCx6odV2p8D6ILilYBIN-dOPeAt8IyjcMw',
    appId: '1:650924033105:ios:334a4226510d3214a62470',
    messagingSenderId: '650924033105',
    projectId: 'fanitmdtest',
    storageBucket: 'fanitmdtest.firebasestorage.app',
    iosBundleId: 'com.example.fanitMdtest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCGwsUhSEdp7IspSBqkGkTTN5hBvW0QJT4',
    appId: '1:650924033105:web:260dae72b526a791a62470',
    messagingSenderId: '650924033105',
    projectId: 'fanitmdtest',
    authDomain: 'fanitmdtest.firebaseapp.com',
    storageBucket: 'fanitmdtest.firebasestorage.app',
    measurementId: 'G-JBH27916TZ',
  );
}
